/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author RC_Student_lab
 */
public class Chatapp extends javax.swing.JPanel {

    /**
     * Creates new form Chatapp
     * 
     * 
     */
    public Chatapp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signup = new javax.swing.JTextField();
        login = new javax.swing.JTextField();
        enteryourusername = new javax.swing.JTextField();
        enteryourpassword = new javax.swing.JTextField();
        enteryourcellphonenumber = new javax.swing.JTextField();
        sendmessage = new javax.swing.JButton();

        signup.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signup.setText("Sign up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });

        login.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        login.setText("Log in");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        enteryourusername.setText("USERNAME:");
        enteryourusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteryourusernameActionPerformed(evt);
            }
        });

        enteryourpassword.setText("PASSWORD:");
        enteryourpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteryourpasswordActionPerformed(evt);
            }
        });

        enteryourcellphonenumber.setText("CELPHONENUMBER:");
        enteryourcellphonenumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteryourcellphonenumberActionPerformed(evt);
            }
        });

        sendmessage.setText("SEND");
        sendmessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(enteryourusername)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(enteryourpassword)
                    .addComponent(enteryourcellphonenumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(sendmessage)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(enteryourusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(enteryourpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enteryourcellphonenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendmessage))
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
       

     



    }//GEN-LAST:event_loginActionPerformed

    private void sendmessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmessageActionPerformed
        // TODO add your handling code here:
       
    
          Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(LoginFrame); 
    //GEN-LAST:event_jButton2ActionPerformed

    }//GEN-LAST:event_sendmessageActionPerformed

    private void enteryourusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteryourusernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_enteryourusernameActionPerformed

    private void enteryourpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteryourpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteryourpasswordActionPerformed

    private void enteryourcellphonenumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteryourcellphonenumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enteryourcellphonenumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enteryourcellphonenumber;
    private javax.swing.JTextField enteryourpassword;
    private javax.swing.JTextField enteryourusername;
    private javax.swing.JTextField login;
    private javax.swing.JButton sendmessage;
    private javax.swing.JTextField signup;
    // End of variables declaration//GEN-END:variables
}
